version: "2"
services:
  fluentd:
    image: bortes/fluentd-elasticsearch:latest
    ports:
      - "24224:24224"

  elasticsearch:
    cap_add:
      - IPC_LOCK
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - cluster.name=app-monitor
      - discovery.zen.ping.unicast.hosts=elasticsearch
      - network.host=_site_
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1

  sysctl:
    environment: 
      - SYSCTL_KEY=vm.max_map_count
      - SYSCTL_VALUE=262144
    image: rawmind/alpine-sysctl:0.1
    network_mode: none
    privileged: true

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.0.0
    ports:
      - "5601:5601"
