.catalog:
  name: Application Monitor
  version: 3.0.0
  description: |
    Generic Application Monitoring Solution
  uuid: application-monitor-0
  minimum_rancher_version: v1.5.5
  questions:
    - variable: HOST_LABEL
      description: |
        Host label where services will run.
      label: Host label (Optional)
      required: false
      type: string
    - variable: ELASTICSEARCH_JAVA_OPTS
      default: -Xms512m -Xmx512m
      description: |
        A Java options for Elasticsearch.
      label: Java options
      required: true
      type: string
